// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/indian_man.glb -o app/assets/3D/indianMan.jsx --root public 
Author: iamandeep361 (https://sketchfab.com/iamandeep361)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-man-1c20d4f362d84953904428aa1696d69d
Title: indian man
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/indian_man.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="01fb08bdfa62458daf7a780b1e2ed909fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="Object_8" />
                  <group name="Object_15" />
                  <group name="Object_20" />
                  <group name="Object_23" />
                  <group name="Object_26" />
                  <group name="Object_29" />
                  <group name="Default_CC_Base_Tongue_Default" />
                  <group name="Default_CC_Base_Body_Default" />
                  <group name="Default_CC_Base_Eye_Default" />
                  <group name="Default_CC_Base_Teeth_Default" />
                  <group name="Default_Chancletas_OBJ_Default" />
                  <group name="Default_model_3_Default" />
                  <group name="Default_RL_Hair_Default" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Default_Std_Tongue_Default} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Default_Std_Skin_Head_Default} skeleton={nodes.Object_9.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Default_Std_Skin_Body_Default} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Default_Std_Skin_Arm_Default} skeleton={nodes.Object_11.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Default_Std_Skin_Leg_Default} skeleton={nodes.Object_12.skeleton} />
                  <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Default_Std_Nails_Default} skeleton={nodes.Object_13.skeleton} />
                  <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Default_Std_Eyelash_Default} skeleton={nodes.Object_14.skeleton} />
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Default_Std_Eye_R_Default} skeleton={nodes.Object_16.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Default_Std_Cornea_R_Default} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Default_Std_Eye_L_Default} skeleton={nodes.Object_18.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Default_Std_Cornea_L_Default} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Default_Std_Upper_Teeth_Default} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Default_Std_Lower_Teeth_Default} skeleton={nodes.Object_22.skeleton} />
                  <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.Default_01_Default_Default} skeleton={nodes.Object_24.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Default_02_Default_Default} skeleton={nodes.Object_25.skeleton} />
                  <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Default_FABRIC_2_FRONT_355549_Default} skeleton={nodes.Object_27.skeleton} />
                  <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.Default_FABRIC_1_FRONT_5079_Default} skeleton={nodes.Object_28.skeleton} />
                  <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Default_RL_Hair_Default} skeleton={nodes.Object_30.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/indian_man.glb')
