// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/indian_teenager.glb -o app/assets/3D/indianTeenager.jsx --root public 
Author: Pixel_Monster (https://sketchfab.com/ar.jethin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-teenager-b2804b40f671431ca7b5cc53b239175e
Title: Indian Teenager
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/indian_teenager.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.914}>
          <group name="6e6ef1032b154bafb6418e534c2494abfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="AvatarRoot">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="AvatarBody" />
                    <group name="AvatarEyelashes" />
                    <group name="AvatarHead" />
                    <group name="AvatarLeftCornea" />
                    <group name="AvatarLeftEyeball" />
                    <group name="AvatarRightCornea" />
                    <group name="AvatarRightEyeball" />
                    <group name="AvatarTeethLower" />
                    <group name="AvatarTeethUpper" />
                    <group name="outfit_bottom" />
                    <group name="outfit_shoes" />
                    <group name="outfit_top" />
                    <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.AvatarBody} skeleton={nodes.Object_7.skeleton} />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.AvatarEyelashes} skeleton={nodes.Object_8.skeleton} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.AvatarHead} skeleton={nodes.Object_9.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.AvatarLeftCornea} skeleton={nodes.Object_10.skeleton} />
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.AvatarLeftEyeball} skeleton={nodes.Object_11.skeleton} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.AvatarRightCornea} skeleton={nodes.Object_12.skeleton} />
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.AvatarRightEyeball} skeleton={nodes.Object_13.skeleton} />
                    <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.AvatarTeethLower} skeleton={nodes.Object_14.skeleton} />
                    <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.AvatarTeethUpper} skeleton={nodes.Object_15.skeleton} />
                    <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.outfit_bottom} skeleton={nodes.Object_16.skeleton} />
                    <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.outfit_shoes} skeleton={nodes.Object_17.skeleton} />
                    <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.outfit_top} skeleton={nodes.Object_18.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/indian_teenager.glb')
