// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/man.glb -o app/assets/3D/man.jsx --root public 
Author: Mcyborg (https://sketchfab.com/Mcyborg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/man-d91475da67924946b3b454daa17639a3
Title: Man
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/man.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.man_Std_Tongue_0.geometry} material={materials.Std_Tongue} />
          <mesh geometry={nodes.man_Std_Skin_Head_0.geometry} material={materials.Std_Skin_Head} />
          <mesh geometry={nodes.man_Std_Skin_Body_0.geometry} material={materials.Std_Skin_Body} />
          <mesh geometry={nodes.man_Std_Skin_Arm_0.geometry} material={materials.Std_Skin_Arm} />
          <mesh geometry={nodes.man_Std_Skin_Leg_0.geometry} material={materials.Std_Skin_Leg} />
          <mesh geometry={nodes.man_Std_Nails_0.geometry} material={materials.Std_Nails} />
          <mesh geometry={nodes.man_Std_Eyelash_0.geometry} material={materials.Std_Eyelash} />
          <mesh geometry={nodes.man_Std_Eye_R_0.geometry} material={materials.Std_Eye_R} />
          <mesh geometry={nodes.man_Std_Cornea_R_0.geometry} material={materials.Std_Cornea_R} />
          <mesh geometry={nodes.man_Std_Eye_L_0.geometry} material={materials.Std_Eye_L} />
          <mesh geometry={nodes.man_Std_Cornea_L_0.geometry} material={materials.Std_Cornea_L} />
          <mesh geometry={nodes.man_Std_Upper_Teeth_0.geometry} material={materials.Std_Upper_Teeth} />
          <mesh geometry={nodes.man_Std_Lower_Teeth_0.geometry} material={materials.Std_Lower_Teeth} />
          <mesh geometry={nodes.man_Std_Eye_Occlusion_R_0.geometry} material={materials.Std_Eye_Occlusion_R} />
          <mesh geometry={nodes.man_Std_Eye_Occlusion_L_0.geometry} material={materials.Std_Eye_Occlusion_L} />
          <mesh geometry={nodes.man_Std_Tearline_R_0.geometry} material={materials.Std_Tearline_R} />
          <mesh geometry={nodes.man_Std_Tearline_L_0.geometry} material={materials.Std_Tearline_L} />
          <mesh geometry={nodes.man_Henley___Longsleeve_0.geometry} material={materials.Henley___Longsleeve} />
          <mesh geometry={nodes.man_Jeans_0.geometry} material={materials.Jeans} />
          <mesh geometry={nodes['man_Slip-ons_0'].geometry} material={materials['Slip-ons']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/man.glb')
