// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/3d_scan_man_1.glb -o app/assets/3D/scanMan1.jsx --root public 
Author: rusttm88 (https://sketchfab.com/rusttm88)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-scan-man-1-ad42febfaeb64aa0992e804acc9e7ccd
Title: 3d scan man 1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/3d_scan_man_1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.908}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.M_3d_scan_man_1} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.M_3d_scan_man_1} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.M_3d_scan_man_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/3d_scan_man_1.glb')
