// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/standing_man.glb -o app/assets/3D/standingMan.jsx --root public 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/standing_man.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.943}>
          <group name="standing_manfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Body" />
                  <group name="clothing" />
                  <group name="Eyelashes" />
                  <group name="Head" />
                  <group name="LeftCornea" />
                  <group name="Object_10" />
                  <group name="Object_12" />
                  <group name="Object_14" />
                  <group name="Object_6" />
                  <group name="Object_8" />
                  <group name="RightCornea" />
                  <group name="shoe_L" />
                  <group name="shoe_R" />
                  <group name="TeethLower" />
                  <group name="TeethUpper" />
                  <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.LeftCornea_map} skeleton={nodes.Object_16.skeleton} />
                  <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.RightCornea_map} skeleton={nodes.Object_17.skeleton} />
                  <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.TeethLower_map} skeleton={nodes.Object_18.skeleton} />
                  <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.TeethLower_map} skeleton={nodes.Object_19.skeleton} />
                  <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Eyelashes_map} skeleton={nodes.Object_20.skeleton} />
                  <skinnedMesh name="StandingMan_Body" geometry={nodes.StandingMan_Body.geometry} material={materials.Mat_Skin_Body} skeleton={nodes.StandingMan_Body.skeleton} />
                  <skinnedMesh name="StandingMan_Bottom" geometry={nodes.StandingMan_Bottom.geometry} material={materials.Mat_Bottom} skeleton={nodes.StandingMan_Bottom.skeleton} />
                  <skinnedMesh name="StandingMan_Head" geometry={nodes.StandingMan_Head.geometry} material={materials.Mat_Skin_Head} skeleton={nodes.StandingMan_Head.skeleton} />
                  <skinnedMesh name="StandingMan_Shoe_L" geometry={nodes.StandingMan_Shoe_L.geometry} material={materials.Mat_Shoes} skeleton={nodes.StandingMan_Shoe_L.skeleton} />
                  <skinnedMesh name="StandingMan_Shoe_R" geometry={nodes.StandingMan_Shoe_R.geometry} material={materials.Mat_Shoes} skeleton={nodes.StandingMan_Shoe_R.skeleton} />
                  <skinnedMesh name="StandingMan_Top" geometry={nodes.StandingMan_Top.geometry} material={materials.Mat_Top} skeleton={nodes.StandingMan_Top.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/standing_man.glb')
